language: ruby
rvm:
  - 2.2.3
before_install:
  - rvm install 2.2.3
install:
  - bundle install --path vendor/bundle
script:
  - bundle exec middleman build
branches:
  only:
  - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
